/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 studio.glb --instance --transform 
Files: studio.glb [530.49KB] > /Users/jalla/Documents/code/timesfour/projects/wooz-experience-shop/public/models/studio-transformed.glb [424.82KB] (20%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/studio-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.studio.geometry} material={nodes.studio.material} position={[0, 1.5, 0]} />
      <mesh geometry={nodes.Splatter_Blue.geometry} material={nodes.Splatter_Blue.material} position={[-1.498, -0.443, -0.35]} rotation={[Math.PI / 2, 0, -0.417]} />
    </group>
  )
}

useGLTF.preload('/studio-transformed.glb')
