/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 studio31okt.glb -d -k 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { useLoader } from "@react-three/fiber";
import vertexShader from "./shaders/studio/vertexShader.glsl";
import fragmentShader from "./shaders/studio/fragmentShader.glsl";

import Effects from "./Effects";

export function Model(props) {
  const { nodes } = useGLTF("/models/studio31okt-comp.glb");

  const bakedFinalTexture = useLoader(THREE.TextureLoader, "/assets/baked.jpg");
  bakedFinalTexture.colorSpace = THREE.SRGBColorSpace;
  bakedFinalTexture.flipY = false;

  const studioMaterial = new THREE.ShaderMaterial({
    uniforms: {
      uBakedDayTexture: new THREE.Uniform(bakedFinalTexture),
    },
    vertexShader,
    fragmentShader,
    side: THREE.DoubleSide,
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        name="studio"
        geometry={nodes.studio.geometry}
        material={studioMaterial}
        position={[0, 1.5, 0]}
      />
      <mesh
        name="Totebag"
        geometry={nodes.Totebag.geometry}
        material={studioMaterial}
        position={[2.852, 0.699, -0.626]}
        rotation={[Math.PI / 2, 0, -1.19]}
      />
      <mesh
        name="Splatter_White"
        geometry={nodes.Splatter_White.geometry}
        material={studioMaterial}
        position={[-0.78, -0.442, 1.139]}
        rotation={[Math.PI / 2, 0, -1.845]}
      />
      <mesh
        name="Splatter_Green"
        geometry={nodes.Splatter_Green.geometry}
        material={studioMaterial}
        position={[-0.45, -0.443, 1.266]}
        rotation={[Math.PI / 2, 0, 1.795]}
      />
      <mesh
        name="Splatter_Blue"
        geometry={nodes.Splatter_Blue.geometry}
        material={studioMaterial}
        position={[-0.115, -0.443, 1.387]}
        rotation={[Math.PI / 2, 0, 1.398]}
      />
      <mesh
        name="Longsleeve_White"
        geometry={nodes.Longsleeve_White.geometry}
        material={studioMaterial}
        position={[-1.645, -0.44, -0.129]}
        rotation={[Math.PI / 2, 0, 3.099]}
      />
      <mesh
        name="Longsleeve_Green"
        geometry={nodes.Longsleeve_Green.geometry}
        material={studioMaterial}
        position={[-1.637, -0.441, -0.365]}
        rotation={[Math.PI / 2, 0, -0.174]}
      />
      <mesh
        name="Longsleeve_Brown"
        geometry={nodes.Longsleeve_Brown.geometry}
        material={studioMaterial}
        position={[-1.649, -0.442, 0.265]}
        rotation={[Math.PI / 2, 0, 0.064]}
      />
      <mesh
        name="Longsleeve_Blue"
        geometry={nodes.Longsleeve_Blue.geometry}
        material={studioMaterial}
        position={[-1.655, -0.439, 0.087]}
        rotation={[Math.PI / 2, 0, 2.946]}
      />
      <mesh
        name="Longsleeve_Black"
        geometry={nodes.Longsleeve_Black.geometry}
        material={studioMaterial}
        position={[-1.65, -0.442, 0.44]}
        rotation={[Math.PI / 2, 0, -0.107]}
      />
      <mesh
        name="Polo_White"
        geometry={nodes.Polo_White.geometry}
        material={studioMaterial}
        position={[-0.786, -0.441, -0.993]}
        rotation={[Math.PI / 2, 0, 0.921]}
      />
      <mesh
        name="Polo_LightBlue"
        geometry={nodes.Polo_LightBlue.geometry}
        material={studioMaterial}
        position={[-0.153, -0.441, -1.325]}
        rotation={[Math.PI / 2, 0, -2.244]}
      />
      <mesh
        name="Polo_Grey"
        geometry={nodes.Polo_Grey.geometry}
        material={studioMaterial}
        position={[-0.334, -0.441, -1.23]}
        rotation={[Math.PI / 2, 0, 0.857]}
      />
      <mesh
        name="Polo_Green"
        geometry={nodes.Polo_Green.geometry}
        material={studioMaterial}
        position={[-0.49, -0.441, -1.148]}
        rotation={[Math.PI / 2, 0, 0.817]}
      />
      <mesh
        name="Polo_Blue"
        geometry={nodes.Polo_Blue.geometry}
        material={studioMaterial}
        position={[-0.643, -0.441, -1.068]}
        rotation={[Math.PI / 2, 0, -2.256]}
      />
      <mesh
        name="Polo_Black"
        geometry={nodes.Polo_Black.geometry}
        material={studioMaterial}
        position={[-0.929, -0.441, -0.912]}
        rotation={[Math.PI / 2, 0, 0.984]}
      />
      <mesh
        name="Hoodie_LightGrey"
        geometry={nodes.Hoodie_LightGrey.geometry}
        material={studioMaterial}
        position={[1.003, -0.441, -1.533]}
        rotation={[Math.PI / 2, 0, -1.292]}
      />
      <mesh
        name="Hoodie_LightGreen"
        geometry={nodes.Hoodie_LightGreen.geometry}
        material={studioMaterial}
        position={[1.227, -0.441, -1.531]}
        rotation={[Math.PI / 2, 0, 1.857]}
      />
      <mesh
        name="Hoodie_DarkGrey"
        geometry={nodes.Hoodie_DarkGrey.geometry}
        material={studioMaterial}
        position={[1.498, -0.441, -1.518]}
        rotation={[Math.PI / 2, 0, -1.016]}
      />
      <mesh
        name="Hoodie_Black"
        geometry={nodes.Hoodie_Black.geometry}
        material={studioMaterial}
        position={[0.7, -0.441, -1.538]}
        rotation={[Math.PI / 2, 0, -1.801]}
      />
    </group>
  );
}

useGLTF.preload("/models/studio31okt-comp.glb");
