/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 studioMat4.glb -d -k 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function StudioMat4(props) {
  const { nodes, materials } = useGLTF("/models/studioMat4.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        name="studio001"
        geometry={nodes.studio001.geometry}
        material={materials.bake_Diffuse}
        position={[0, 1.5, 0]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Splatter_Blue_High001"
        geometry={nodes.Splatter_Blue_High001.geometry}
        material={materials.bake_Diffuse}
        position={[-0.093, 0.846, 1.382]}
        rotation={[Math.PI / 2, 0, 1.398]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Splatter_Green_High001"
        geometry={nodes.Splatter_Green_High001.geometry}
        material={materials.bake_Diffuse}
        position={[-0.428, 0.846, 1.27]}
        rotation={[Math.PI / 2, 0, 1.795]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Splatter_White_High001"
        geometry={nodes.Splatter_White_High001.geometry}
        material={materials.bake_Diffuse}
        position={[-0.801, 0.847, 1.147]}
        rotation={[Math.PI / 2, 0, -1.845]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Longsleeve_Black_High001"
        geometry={nodes.Longsleeve_Black_High001.geometry}
        material={materials.bake_Diffuse}
        position={[0.669, 0.766, -1.513]}
        rotation={[Math.PI / 2, 0, 1.346]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Longsleeve_Brown_High001"
        geometry={nodes.Longsleeve_Brown_High001.geometry}
        material={materials.bake_Diffuse}
        position={[0.889, 0.766, -1.544]}
        rotation={[Math.PI / 2, 0, 1.676]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Longsleeve_Blue_High001"
        geometry={nodes.Longsleeve_Blue_High001.geometry}
        material={materials.bake_Diffuse}
        position={[1.076, 0.769, -1.562]}
        rotation={[Math.PI / 2, 0, -1.884]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Longsleeve_White_High001"
        geometry={nodes.Longsleeve_White_High001.geometry}
        material={materials.bake_Diffuse}
        position={[1.287, 0.768, -1.579]}
        rotation={[Math.PI / 2, 0, -1.731]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Longsleeve_Green_High001"
        geometry={nodes.Longsleeve_Green_High001.geometry}
        material={materials.bake_Diffuse}
        position={[1.47, 0.767, -1.594]}
        rotation={[Math.PI / 2, 0, 1.28]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Polo2_Black_High001"
        geometry={nodes.Polo2_Black_High001.geometry}
        material={materials.bake_Diffuse}
        position={[-1.024, 0.815, -1.049]}
        rotation={[Math.PI / 2, 0, 0.984]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Polo2_White_High001"
        geometry={nodes.Polo2_White_High001.geometry}
        material={materials.bake_Diffuse}
        position={[-0.88, 0.815, -1.129]}
        rotation={[Math.PI / 2, 0, 0.921]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Polo2_Blue_High001"
        geometry={nodes.Polo2_Blue_High001.geometry}
        material={materials.bake_Diffuse}
        position={[-0.716, 0.815, -1.215]}
        rotation={[Math.PI / 2, 0, -2.256]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Polo2_Green_High001"
        geometry={nodes.Polo2_Green_High001.geometry}
        material={materials.bake_Diffuse}
        position={[-0.584, 0.815, -1.283]}
        rotation={[Math.PI / 2, 0, 0.817]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Polo2_Grey_High001"
        geometry={nodes.Polo2_Grey_High001.geometry}
        material={materials.bake_Diffuse}
        position={[-0.428, 0.815, -1.366]}
        rotation={[Math.PI / 2, 0, 0.857]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Polo2_LightBlue_High001"
        geometry={nodes.Polo2_LightBlue_High001.geometry}
        material={materials.bake_Diffuse}
        position={[-0.226, 0.815, -1.472]}
        rotation={[Math.PI / 2, 0, -2.244]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Hoodie_LightGreen_High001"
        geometry={nodes.Hoodie_LightGreen_High001.geometry}
        material={materials.bake_Diffuse}
        position={[-1.507, 0.838, -0.083]}
        rotation={[Math.PI / 2, 0, 0.286]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Hoodie_DarkGrey_High001"
        geometry={nodes.Hoodie_DarkGrey_High001.geometry}
        material={materials.bake_Diffuse}
        position={[-1.493, 0.838, -0.354]}
        rotation={[Math.PI / 2, 0, -2.505]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Hoodie_LightGrey_High001"
        geometry={nodes.Hoodie_LightGrey_High001.geometry}
        material={materials.bake_Diffuse}
        position={[-1.493, 0.838, 0.216]}
        rotation={[Math.PI / 2, 0, -0.293]}
        castShadow
        receiveShadow
      />
      <mesh
        name="Hoodie_Black_High001"
        geometry={nodes.Hoodie_Black_High001.geometry}
        material={materials.bake_Diffuse}
        position={[-1.513, 0.838, 0.444]}
        rotation={[Math.PI / 2, 0, 2.911]}
        castShadow
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload("/models/studioMat4.glb");
